### ISSUE TITLE
Microphone mute dosent work

### ISSUE THREAD

**Issue by YoussefHachicha** [GetStream/webrtc-android#181]
when I mute my microphone the other user can still hear your voice

**Comment by skydoves** [comment]
Would you share what kinds of method did you use? The Stream SDK doesn't face any problem following this way: https://github.com/GetStream/stream-video-android/blob/develop/stream-video-android-core/src/main/kotlin/io/getstream/video/android/core/MediaManager.kt#L329

**Comment by YoussefHachicha** [comment]
I used the implementation of this https://github.com/GetStream/webrtc-in-jetpack-compose
I add this to the code `localAudioTrack.setEnabled(enabled)` and it worked thanks for your response
```
  override fun enableMicrophone(enabled: Boolean) {
        localAudioTrack.setEnabled(enabled)
        audioManager?.isMicrophoneMute = !enabled
    }
```
