### ISSUE TITLE
Missing Changelog

### ISSUE THREAD

**Issue by eyedol** [GetStream/webrtc-android#2]
Possible to include change logs for the releases and also if you could add which version or commit of the webRTC for Android from Google was compiled. Would be great to know what we're working with as we integrate these pre-builds 🙏

**Comment by skydoves** [comment]
Hey @eyedol, thanks for filing this issue. We're planning to create a Changelog, which reflects the commit & versions or branch information in the next release. Please stay tuned and watch this repository! 😄

**Comment by skydoves** [comment]
Hi @eyedol, the latest release contains changelog about the version and histories of the WebRTC for Android: https://github.com/GetStream/webrtc-android/releases/tag/1.1.0

Thanks for reporting this issue!

**Comment by eyedol** [comment]
Great. And thanks for including changelogs in the releases now.
