### ISSUE TITLE
[QUESTION] Merge strategy from latest Google libwebrtc

### ISSUE THREAD

**Issue by hassanctech** [GetStream/webrtc-android#58]
I have a question, we're looking for a pre-built version of libwebrtc for Android and want to know how to find out what the latest version of Google's libwebrtc is in this repo?  Suppose there is a security vulnerability discovered in libwebrtc that's fixed in another commit, I would like to know if the vulnerability itself is present here and if the fix made it here.  How can I know this information?  Is there an official merging strategy here?

**Comment by DanielNovak** [comment]
@hassanctech Sorry for the late reply. We will try to make this more transparent in the coming 1-2 weeks. We are working on a new WebRTC build based on version m114 and the native part will be available in a new public repo and you can then also see any patches that we applied on top of it.

**Comment by skydoves** [comment]
Hi @hassanctech , the latest release contains changelog about the version and histories of the WebRTC for Android: https://github.com/GetStream/webrtc-android/releases/tag/1.1.0

Thanks for reporting this issue!
