### ISSUE TITLE
Add option to change aspect of Image [VideoTextureViewRenderer]

### ISSUE THREAD

**Issue by tiagomartinho** [GetStream/webrtc-android#6]
I'm having trouble changing the aspect of the image with the VideoTextureViewRenderer, previously I was using setScalingType with fit and fill on the SurfaceViewRenderer, but now I'm not sure how to do it, maybe an option could be added to VideoTextureViewRenderer?

**Comment by skydoves** [comment]
Hey @tiagomartinho, it has been included in version 1.0.2! You can use the `setScalingType` now. Please let me know if you have additional issues with the new version. Thank you!

**Comment by tiagomartinho** [comment]
thank you so much! will test it further and let you know. thanks again for the awesome project!

**Comment by tiagomartinho** [comment]
Hi @skydoves ! Actually the update 1.0.2 didn't work for me.

I'm trying to use setScalingType(SCALE_ASPECT_FIT) without success, the image still fills the entire screen.

Maybe I'm misusing VideoTextureViewRenderer, I'm doing:
`    <io.getstream.webrtc.android.ui.VideoTextureViewRenderer
        android:id="@+id/new_mirror_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />`

**Comment by tiagomartinho** [comment]
That was the problem! Using the constraints fixed it

`    <io.getstream.webrtc.android.ui.VideoTextureViewRenderer
        android:id="@+id/new_mirror_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        />`

**Comment by skydoves** [comment]
@tiagomartinho Happy to hear that it's working well!
